library identifier: 'jenkins-global-lib'

kube().pod( "kubernetes", "kubernetes-vault-test" ).
    withServiceAccount( "jenkins" ).
node {
    stage('secret') {
        def luggage = vault().secret( "secret/data/luggage" )
        echo "Got secret: ${luggage}"
    }
}
