library identifier: 'jenkins-global-lib'

kube().pod( "kubernetes", "kubernetes-vault-test" ).
    withServiceAccount( "jenkins" ).
node {
    stage('secret') {
        def secrets = [ 
            [ 
                path: 'secret/luggage',
                secretValues: [ 
                    [envVar: 'luggage', vaultKey: 'combination'] 
                ] 
            ]
        ]
        vault().withSecrets( secrets ) {
            if( env.luggage == '12345' ) {
                echo "Got expected secret"
            }
            else {
                echo "Did not get expected value"
            }
            sh 'echo $luggage'
        } 
    }
}
