name: Test Ansible
on: [pull_request]

jobs:
  build:
    name: Test Ansible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Build Dependencies
        # Has to delete msodbcsql17 because it requires
        # to accept Microsoft EULA on packages upgrade
        run: >
          sudo apt-get update -qq &&
          sudo apt-get install -qq python-apt python-pycurl &&
          pip install ansible &&
          sudo apt-get -qq purge msodbcsql17

      - name: Syntax Check
        working-directory: ./packer/ansible
        run: ansible-playbook --syntax-check -i 'localhost,' site.yml

      - name: First Run
        working-directory: ./packer/ansible
        run: >
          ansible-playbook -i 'localhost,' site.yml
          --connection=local
          --extra-vars "vault_version=1.2.3
          vault_version_checksum=sha256:fe15676404aff35cb45f7c957f90491921b9269d79a8f933c5a36e26a431bfc4"

      - name: Check Vault & Version
        run: >
          which vault &&
          vault version | grep -q 'Vault v1.2.3'
